# this is the db container
db:
  image: postgres
  ports:
    - "5432:5432"
  environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=postgres

# This is the bundle install container, all gems will be installed here
box:
  image: busybox
  volumes:
    - /box

# This is the rails container, where your app will be delivered
web: &default
  build: .
  command: ./script/start.sh
  volumes:
    - .:/usr/src/app
  volumes_from:
    - box
  hostname: padawan
  ports:
    - "3000:3000"
  links:
    - db
    - mailcatcher
  environment:
    - DB_USER=DB_1_ENV_POSTGRES_USER
    - DB_PASSWORD=DB_1_ENV_POSTGRES_PASSWORD
    - DB_HOST=db
    - MAILCATCHER_HOST=mailcatcher

# This will pull a separate image for mailcatcher
mailcatcher:
  hostname: mailcatcher
  image: "schickling/mailcatcher"
  command: mailcatcher -f --ip=0.0.0.0
  ports:
    - "1080:1080"
    - "1025:1025"
